version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: barbershop_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: barbershop
      POSTGRES_PASSWORD: barbershop
      POSTGRES_DB: barbershop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
